// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0yyfx0DPqYS05xliOLBsQTPkafO2_xx4',
    appId: '1:993346210960:web:bcf56d7be9948d3ba15c15',
    messagingSenderId: '993346210960',
    projectId: 'workerapp-2e6c8',
    authDomain: 'workerapp-2e6c8.firebaseapp.com',
    storageBucket: 'workerapp-2e6c8.appspot.com',
    measurementId: 'G-EPRP4RT94J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGioNiNryXbtOuacKQWrTr4CkK-QU_mgI',
    appId: '1:993346210960:android:c6bacccb2da6daeaa15c15',
    messagingSenderId: '993346210960',
    projectId: 'workerapp-2e6c8',
    storageBucket: 'workerapp-2e6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5MXOh_zFSXwtcS1a46FS7tEfNnLfwAf8',
    appId: '1:993346210960:ios:4df1969accd38950a15c15',
    messagingSenderId: '993346210960',
    projectId: 'workerapp-2e6c8',
    storageBucket: 'workerapp-2e6c8.appspot.com',
    iosBundleId: 'com.example.workerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5MXOh_zFSXwtcS1a46FS7tEfNnLfwAf8',
    appId: '1:993346210960:ios:4df1969accd38950a15c15',
    messagingSenderId: '993346210960',
    projectId: 'workerapp-2e6c8',
    storageBucket: 'workerapp-2e6c8.appspot.com',
    iosBundleId: 'com.example.workerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0yyfx0DPqYS05xliOLBsQTPkafO2_xx4',
    appId: '1:993346210960:web:3ca6b152d92defcfa15c15',
    messagingSenderId: '993346210960',
    projectId: 'workerapp-2e6c8',
    authDomain: 'workerapp-2e6c8.firebaseapp.com',
    storageBucket: 'workerapp-2e6c8.appspot.com',
    measurementId: 'G-GFY2EQZ704',
  );
}
